services:

  migrate:
    image: migrate/migrate
    network_mode: "host"
    volumes:
      - ./migrations:/migrations
    entrypoint: [ "migrate", "-path", "/migrations", "-database", "mysql://test:test@tcp(localhost:3306)/test"]

  db:
    image: mysql:8
    network_mode: "host"
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
